describe('The Home Page', () => {
    it('successfully loads', () => {
        cy.intercept('POST', 'http://localhost:8787/site/settings', [])
        cy.intercept('POST', 'http://localhost:8787/site/frontpage', [])
        cy.visit('/')
    })
    it('has visible hero image', () => {
        cy.get('.hero').should('be.visible')
    })
    it('has page header', () => {
        cy.get('.page-header')
    })
    it('page header matches intro title', () => {
        cy.get('.page-header').should('have.text', 'Welcome To Grace Baptist Church of Blue Bell')
    })
    it('matches section 0', () => {
        cy.get('#info-0')
        .find('.info-header')
        .should('have.text', 'Celebrating 45 Years in Blue Bell')
        cy.get('#info-0')
        .find('.info-sub-header')
        .should('have.text', 'Trying out a sub-header')
        cy.get('#info-0')
        .find('.info-text>p')
        .should('have.text', 'Because of the uptick in COVID cases in Montgomery County and the state, we are returning to virtual worship services only (no in-person). Contact us for information about how to join via Zoom. Just because we can’t meet at our church building regularly like we did before, doesn’t mean our church, and our faith, and our God isn’t alive and thriving. We are meeting regularly via Zoom for worship, praise, small groups, bible study, and fellowship. Please join us in praying for all affected by COVID-19 and racial discrimination, and those who are suffering economically during this time. If you would like to participate in any of our worship and praise activities please contact us at staff@gbcbb.org or gbcprayerwarriors@gmail.com.')
    })
    it('matches section 1', () => {
        cy.get('#info-1')
        .find('.info-header')
        .should('have.text', 'Join Us')
        cy.get('#info-1')
        .find('.info-sub-header')
        .should('have.text', '')
        cy.get('#info-1')
        .find('.info-text>p')
        .contains('9:30 AM Sunday School. (At this time only Wired Word, Youth and Young Adult classes are meeting. Contact Brady Rennix or Joan Frizzell for Zoom info or staff@gbcbb.org)')
        cy.get('#info-1')
        .find('.info-text>p')
        .contains('10:45 AM Worship Service Graceland 2nd Hour for children (K-3rd grade) during the worship service. Pre-school childcare provided.')
    })
    it('matches section 2', () => {
        cy.get('#info-2')
        .find('.info-header')
        .should('have.text', 'Find Us')
        cy.get('#info-2')
        .find('.info-sub-header')
        .should('have.text', '')
        cy.get('#info-2')
        .find('.info-text>p')
        .contains('437 Skippack Pike')
        cy.get('#info-2')
        .find('.info-text>p')
        .contains('P.O. Box 122')
        cy.get('#info-2')
        .find('.info-text>p')
        .contains('Blue Bell, PA 19422')
        cy.get('#info-2')
        .find('.info-text>p')
        .contains('215-628-2077')
        cy.get('#info-2')
        .find('img')
    })
  })